#!/bin/bash

if [ -z "$MyOrg" ]
then
	sudo cp keyboard /etc/default/keyboard
	sudo cp lightdm,conf /etc/lightdm/lightdm.conf
	mv $HOME/.bashrc $HOME/.bashrc.old
	ln -sr .bashrc $HOME/
	ln -sr .bashrc.d $HOME/
	ln -sr .tmux.conf $HOME/
	ln -sr .Xdefault $HOME/
	ln -sr .Xdefault.d $HOME/
	sudo apt install -y \
		ctags \
		lightdm \
		i3 \
		network-manager-gnome \
		thunar \
		fonts-font-awesome \
		tmux \
		vim \
		zathura
	ln -sr .vimrc $HOME/
	vim -c PluginInstall  -c quitall
	mv $HOME/.config/i3 $HOME/.config/i3.old
	ln -sr i3 $HOME/.config/i3
fi
